# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pip install aws-cli
  displayName: 'Install AWS CLI'

- script: |
    npm --prefix frontend install
    npm --prefix frontend run build
  displayName: 'npm install and build'

- script: |
    npm --prefix frontend run deploy
  displayName: 'Sync react build with s3'
