# use this file to run the container locally
version: '3.0'
services: 
    backend:
        build: .
        ports: 
            - "8080:4000"
        env_file: 
            - ./backend/.env.production
        environment:
            - NODE_ENV=production
