# use this file to run the container locally
version: '3.0'
services: 
    backend:
        build: .
        ports: 
            - "4000:4000"
        env_file: 
            - ./backend/.env.development
        environment:
            - NODE_ENV=development
