# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key            = "./terraform.tfstate"
    region         = "ap-southeast-2"
    bucket         = "terraform-state"
    dynamodb_table = "terraform-remote-state-lock-table"
    encrypt        = true
  }
}
